import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const font = Cairo({
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Marvel eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <nav className='mb-10 h-20 bg-zinc-300'></nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
