import type { Metadata } from "next";
import { Noto_Kufi_Arabic } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

const font = Noto_Kufi_Arabic({
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Marvel eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <Navbar />
        <main>{children}</main>
        <footer className='mt-10 h-80 bg-muted'></footer>
      </body>
    </html>
  );
}
